version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapi_database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapi_database

  strapi_database:
    container_name: strapi_database
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - strapi

  # api:
  #   container_name: api_pac
  #   platform: linux/amd64 #for platform error on Apple M1 chips
  #   build: ./api
  #   env_file: .env
  #   volumes:
  #     - strapi-data:/var/lib/postgresql/data/ #using a volume
  #
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
